export type ImportedStandardDefinition = {
  code: string;
  checkpointLabel: string;
  checkpointDays: number | null;
  storageCondition: string;
  role: "STANDARD" | "MICROBIOLOGY" | "REFERENCE";
  sortOrder: number;
};

export const importedStandardPlans: Record<string, ImportedStandardDefinition[]> = {
  "Produkty wrażliwe mikrobiologicznie": [
    { code: "Z03", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "STANDARD", sortOrder: 1 },
    { code: "ZRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "REFERENCE", sortOrder: 2 },
    { code: "ZRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "REFERENCE", sortOrder: 3 },
    { code: "R00a", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 4 },
    { code: "R00b", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 5 },
    { code: "R03a", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 6 },
    { code: "R03b", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 7 },
    { code: "R06a", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 8 },
    { code: "R06b", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 9 },
    { code: "R09", checkpointLabel: "9M", checkpointDays: 270, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 10 },
    { code: "R12", checkpointLabel: "12M", checkpointDays: 360, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 11 },
    { code: "R18", checkpointLabel: "18M", checkpointDays: 540, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 12 },
    { code: "R24a", checkpointLabel: "24M", checkpointDays: 720, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 13 },
    { code: "R24b", checkpointLabel: "24M", checkpointDays: 720, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 14 },
    { code: "R36a", checkpointLabel: "36M", checkpointDays: 1080, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 15 },
    { code: "R36b", checkpointLabel: "36M", checkpointDays: 1080, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 16 },
    { code: "RRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "RT (20-25°C)", role: "REFERENCE", sortOrder: 17 },
    { code: "RRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "RT (20-25°C)", role: "REFERENCE", sortOrder: 18 },
    { code: "C01a", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 19 },
    { code: "C01b", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "MICROBIOLOGY", sortOrder: 20 },
    { code: "C03a", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 21 },
    { code: "C03b", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "MICROBIOLOGY", sortOrder: 22 },
    { code: "C06a", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 23 },
    { code: "C06b", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "40°C ± 2°C", role: "MICROBIOLOGY", sortOrder: 24 },
    { code: "CRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "40°C ± 2°C", role: "REFERENCE", sortOrder: 25 },
    { code: "CRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "40°C ± 2°C", role: "REFERENCE", sortOrder: 26 },
  ],
  "Filtry UV": [
    { code: "Z03", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "STANDARD", sortOrder: 1 },
    { code: "ZRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "REFERENCE", sortOrder: 2 },
    { code: "ZRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "REFERENCE", sortOrder: 3 },
    { code: "R00a", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 4 },
    { code: "R00b", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 5 },
    { code: "R03a", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 6 },
    { code: "R03b", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 7 },
    { code: "R06a", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 8 },
    { code: "R06b", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 9 },
    { code: "R12", checkpointLabel: "12M", checkpointDays: 360, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 10 },
    { code: "R18", checkpointLabel: "18M", checkpointDays: 540, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 11 },
    { code: "R24a", checkpointLabel: "24M", checkpointDays: 720, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 12 },
    { code: "R24b", checkpointLabel: "24M", checkpointDays: 720, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 13 },
    { code: "R36a", checkpointLabel: "36M", checkpointDays: 1080, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 14 },
    { code: "R36b", checkpointLabel: "36M", checkpointDays: 1080, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 15 },
    { code: "RRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "RT (20-25°C)", role: "REFERENCE", sortOrder: 16 },
    { code: "RRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "RT (20-25°C)", role: "REFERENCE", sortOrder: 17 },
    { code: "C01a", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 18 },
    { code: "C01b", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "MICROBIOLOGY", sortOrder: 19 },
    { code: "C03a", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 20 },
    { code: "C03b", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "MICROBIOLOGY", sortOrder: 21 },
    { code: "C06a", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 22 },
    { code: "C06b", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "40°C ± 2°C", role: "MICROBIOLOGY", sortOrder: 23 },
    { code: "CRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "40°C ± 2°C", role: "REFERENCE", sortOrder: 24 },
    { code: "CRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "40°C ± 2°C", role: "REFERENCE", sortOrder: 25 },
    { code: "H01", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "50°C ± 2°C", role: "STANDARD", sortOrder: 26 },
    { code: "H03a", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "50°C ± 2°C", role: "STANDARD", sortOrder: 27 },
    { code: "H03b", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "50°C ± 2°C", role: "MICROBIOLOGY", sortOrder: 28 },
    { code: "HRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "50°C ± 2°C", role: "REFERENCE", sortOrder: 29 },
    { code: "HRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "50°C ± 2°C", role: "REFERENCE", sortOrder: 30 },
  ],
  "Wyroby medyczne": [
    { code: "Z03a", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "STANDARD", sortOrder: 1 },
    { code: "Z03b", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "MICROBIOLOGY", sortOrder: 2 },
    { code: "Z06", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "STANDARD", sortOrder: 3 },
    { code: "ZRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "REFERENCE", sortOrder: 4 },
    { code: "ZRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "REFERENCE", sortOrder: 5 },
    { code: "R00a", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 6 },
    { code: "R00b", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 7 },
    { code: "R03a", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 8 },
    { code: "R03b", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 9 },
    { code: "R06a", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 10 },
    { code: "R06b", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 11 },
    { code: "R09", checkpointLabel: "9M", checkpointDays: 270, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 12 },
    { code: "R12a", checkpointLabel: "12M", checkpointDays: 360, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 13 },
    { code: "R12b", checkpointLabel: "12M", checkpointDays: 360, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 14 },
    { code: "R18a", checkpointLabel: "18M", checkpointDays: 540, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 15 },
    { code: "R18b", checkpointLabel: "18M", checkpointDays: 540, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 16 },
    { code: "R24a", checkpointLabel: "24M", checkpointDays: 720, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 17 },
    { code: "R24b", checkpointLabel: "24M", checkpointDays: 720, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 18 },
    { code: "R36a", checkpointLabel: "36M", checkpointDays: 1080, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 19 },
    { code: "R36b", checkpointLabel: "36M", checkpointDays: 1080, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 20 },
    { code: "RRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "RT (20-25°C)", role: "REFERENCE", sortOrder: 21 },
    { code: "RRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "RT (20-25°C)", role: "REFERENCE", sortOrder: 22 },
    { code: "B01a", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "45°C ± 2°C/ 75% RH", role: "STANDARD", sortOrder: 23 },
    { code: "B01b", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "45°C ± 2°C/ 75% RH", role: "MICROBIOLOGY", sortOrder: 24 },
    { code: "B03a", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "45°C ± 2°C/ 75% RH", role: "STANDARD", sortOrder: 25 },
    { code: "B03b", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "45°C ± 2°C/ 75% RH", role: "MICROBIOLOGY", sortOrder: 26 },
    { code: "B06a", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "45°C ± 2°C/ 75% RH", role: "STANDARD", sortOrder: 27 },
    { code: "B06b", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "45°C ± 2°C/ 75% RH", role: "MICROBIOLOGY", sortOrder: 28 },
    { code: "BRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "45°C ± 2°C/ 75% RH", role: "REFERENCE", sortOrder: 29 },
    { code: "BRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "45°C ± 2°C/ 75% RH", role: "REFERENCE", sortOrder: 30 },
  ],
  "Produkty niewrażliwe mikrobiologicznie": [
    { code: "Z03", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "STANDARD", sortOrder: 1 },
    { code: "ZRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "REFERENCE", sortOrder: 2 },
    { code: "ZRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "REFERENCE", sortOrder: 3 },
    { code: "R00a", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 4 },
    { code: "R03a", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 5 },
    { code: "R06a", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 6 },
    { code: "R09", checkpointLabel: "9M", checkpointDays: 270, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 7 },
    { code: "R12", checkpointLabel: "12M", checkpointDays: 360, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 8 },
    { code: "R18", checkpointLabel: "18M", checkpointDays: 540, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 9 },
    { code: "R24a", checkpointLabel: "24M", checkpointDays: 720, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 10 },
    { code: "R36a", checkpointLabel: "36M", checkpointDays: 1080, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 11 },
    { code: "RRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "RT (20-25°C)", role: "REFERENCE", sortOrder: 12 },
    { code: "RRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "RT (20-25°C)", role: "REFERENCE", sortOrder: 13 },
    { code: "C01a", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 14 },
    { code: "C03a", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 15 },
    { code: "C06a", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 16 },
    { code: "CRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "40°C ± 2°C", role: "REFERENCE", sortOrder: 17 },
    { code: "CRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "40°C ± 2°C", role: "REFERENCE", sortOrder: 18 },
  ],
  "Standard WD-40_3M": [
    { code: "R00.1", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 1 },
    { code: "R00.2", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 2 },
    { code: "R00.3", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 3 },
    { code: "R00.4", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 4 },
    { code: "R00.5", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 5 },
    { code: "R00.6", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 6 },
    { code: "R01.1", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 7 },
    { code: "R01.2", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 8 },
    { code: "R01.3", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 9 },
    { code: "R01.4", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 10 },
    { code: "R02.1", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 11 },
    { code: "R02.2", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 12 },
    { code: "R02.3", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 13 },
    { code: "R02.4", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 14 },
    { code: "R03.1", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 15 },
    { code: "R03.2", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 16 },
    { code: "R03.3", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 17 },
    { code: "R03.4", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 18 },
    { code: "C01.1", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 19 },
    { code: "C01.2", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 20 },
    { code: "C01.3", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 21 },
    { code: "C01.4", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 22 },
    { code: "C02.1", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 23 },
    { code: "C02.2", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 24 },
    { code: "C02.3", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 25 },
    { code: "C02.4", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 26 },
    { code: "C03.1", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 27 },
    { code: "C03.2", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 28 },
    { code: "C03.3", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 29 },
    { code: "C03.4", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 30 },
  ],
  "Standard WD-40_60M": [
    { code: "R00.1", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 1 },
    { code: "R00.2", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 2 },
    { code: "R00.3", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 3 },
    { code: "R00.4", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 4 },
    { code: "R00.5", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 5 },
    { code: "R00.6", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 6 },
    { code: "R01.1", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 7 },
    { code: "R01.2", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 8 },
    { code: "R01.3", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 9 },
    { code: "R01.4", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 10 },
    { code: "R02.1", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 11 },
    { code: "R02.2", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 12 },
    { code: "R02.3", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 13 },
    { code: "R02.4", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 14 },
    { code: "R03.1", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 15 },
    { code: "R03.2", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 16 },
    { code: "R03.3", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 17 },
    { code: "R03.4", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 18 },
    { code: "R04.1", checkpointLabel: "4M", checkpointDays: 120, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 19 },
    { code: "R04.2", checkpointLabel: "4M", checkpointDays: 120, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 20 },
    { code: "R04.3", checkpointLabel: "4M", checkpointDays: 120, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 21 },
    { code: "R04.4", checkpointLabel: "4M", checkpointDays: 120, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 22 },
    { code: "R06.1", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 23 },
    { code: "R06.2", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 24 },
    { code: "R06.3", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 25 },
    { code: "R06.4", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 26 },
    { code: "R12.1", checkpointLabel: "12M", checkpointDays: 360, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 27 },
    { code: "R12.2", checkpointLabel: "12M", checkpointDays: 360, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 28 },
    { code: "R12.3", checkpointLabel: "12M", checkpointDays: 360, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 29 },
    { code: "R12.4", checkpointLabel: "12M", checkpointDays: 360, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 30 },
    { code: "R18.1", checkpointLabel: "18M", checkpointDays: 540, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 31 },
    { code: "R18.2", checkpointLabel: "18M", checkpointDays: 540, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 32 },
    { code: "R18.3", checkpointLabel: "18M", checkpointDays: 540, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 33 },
    { code: "R18.4", checkpointLabel: "18M", checkpointDays: 540, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 34 },
    { code: "R24.1", checkpointLabel: "24M", checkpointDays: 720, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 35 },
    { code: "R24.2", checkpointLabel: "24M", checkpointDays: 720, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 36 },
    { code: "R24.3", checkpointLabel: "24M", checkpointDays: 720, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 37 },
    { code: "R24.4", checkpointLabel: "24M", checkpointDays: 720, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 38 },
    { code: "R30.1", checkpointLabel: "30M", checkpointDays: 900, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 39 },
    { code: "R30.2", checkpointLabel: "30M", checkpointDays: 900, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 40 },
    { code: "R30.3", checkpointLabel: "30M", checkpointDays: 900, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 41 },
    { code: "R30.4", checkpointLabel: "30M", checkpointDays: 900, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 42 },
    { code: "R36.1", checkpointLabel: "36M", checkpointDays: 1080, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 43 },
    { code: "R36.2", checkpointLabel: "36M", checkpointDays: 1080, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 44 },
    { code: "R36.3", checkpointLabel: "36M", checkpointDays: 1080, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 45 },
    { code: "R36.4", checkpointLabel: "36M", checkpointDays: 1080, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 46 },
    { code: "R48.1", checkpointLabel: "48M", checkpointDays: 1440, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 47 },
    { code: "R48.2", checkpointLabel: "48M", checkpointDays: 1440, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 48 },
    { code: "R48.3", checkpointLabel: "48M", checkpointDays: 1440, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 49 },
    { code: "R48.4", checkpointLabel: "48M", checkpointDays: 1440, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 50 },
    { code: "R60.1", checkpointLabel: "60M", checkpointDays: 1800, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 51 },
    { code: "R60.2", checkpointLabel: "60M", checkpointDays: 1800, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 52 },
    { code: "R60.3", checkpointLabel: "60M", checkpointDays: 1800, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 53 },
    { code: "R60.4", checkpointLabel: "60M", checkpointDays: 1800, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 54 },
    { code: "C01.1", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 55 },
    { code: "C01.2", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 56 },
    { code: "C01.3", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 57 },
    { code: "C01.4", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 58 },
    { code: "C02.1", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 59 },
    { code: "C02.2", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 60 },
    { code: "C02.3", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 61 },
    { code: "C02.4", checkpointLabel: "2M", checkpointDays: 60, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 62 },
    { code: "C03.1", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 63 },
    { code: "C03.2", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 64 },
    { code: "C03.3", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 65 },
    { code: "C03.4", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 66 },
  ],
  "Standardowe 3M": [
    { code: "Z03", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "STANDARD", sortOrder: 1 },
    { code: "ZRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "REFERENCE", sortOrder: 2 },
    { code: "ZRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "5°C ± 3°C (pref. 3°C)", role: "REFERENCE", sortOrder: 3 },
    { code: "R00a", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 4 },
    { code: "R00b", checkpointLabel: "0M", checkpointDays: 0, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 5 },
    { code: "R03a", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 6 },
    { code: "R03b", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 7 },
    { code: "R06a", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "STANDARD", sortOrder: 8 },
    { code: "R06b", checkpointLabel: "6M", checkpointDays: 180, storageCondition: "RT (20-25°C)", role: "MICROBIOLOGY", sortOrder: 9 },
    { code: "RRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "RT (20-25°C)", role: "REFERENCE", sortOrder: 10 },
    { code: "RRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "RT (20-25°C)", role: "REFERENCE", sortOrder: 11 },
    { code: "C01a", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 12 },
    { code: "C01b", checkpointLabel: "1M", checkpointDays: 30, storageCondition: "40°C ± 2°C", role: "MICROBIOLOGY", sortOrder: 13 },
    { code: "C03a", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "STANDARD", sortOrder: 14 },
    { code: "C03b", checkpointLabel: "3M", checkpointDays: 90, storageCondition: "40°C ± 2°C", role: "MICROBIOLOGY", sortOrder: 15 },
    { code: "CRFa", checkpointLabel: "REF", checkpointDays: null, storageCondition: "40°C ± 2°C", role: "REFERENCE", sortOrder: 16 },
    { code: "CRFb", checkpointLabel: "REF", checkpointDays: null, storageCondition: "40°C ± 2°C", role: "REFERENCE", sortOrder: 17 },
  ],
};
