import Link from "next/link";
import { notFound } from "next/navigation";
import { CriterionKind, Evaluation, SampleRole, StudyStatus, UserRole } from "@/generated/prisma/client";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { AppShell } from "@/components/app-shell";

const statusLabel: Record<StudyStatus, string> = { DRAFT: "Robocze", ACTIVE: "W realizacji", COMPLETED: "Zakończone", CANCELLED: "Anulowane", INTERRUPTED: "Przerwane" };
function criterionText(v: { minValue: number | null; maxValue: number | null; expectedText: string | null; expectedBoolean: boolean | null } | null | undefined) {
  if (!v) return "Informacyjnie";
  if (v.minValue != null || v.maxValue != null) return `${v.minValue ?? "−∞"} – ${v.maxValue ?? "+∞"}`;
  if (v.expectedText != null) return v.expectedText;
  if (v.expectedBoolean != null) return v.expectedBoolean ? "TAK" : "NIE";
  return "—";
}
function resultText(result: { state: string; numericValue: number | null; textValue: string | null; booleanValue: boolean | null; notPerformedReason: string | null }, unit: string | null) {
  if (result.state === "NOT_PERFORMED") return `Nie wykonano · ${result.notPerformedReason || "brak powodu"}`;
  if (result.numericValue != null) return `${result.numericValue}${unit ? ` ${unit}` : ""}`;
  if (result.textValue != null) return result.textValue;
  if (result.booleanValue != null) return result.booleanValue ? "TAK" : "NIE";
  return "—";
}
function weekEnd(date: Date) { const value = new Date(date); value.setHours(23,59,59,999); const day = value.getDay(); value.setDate(value.getDate() + (day === 0 ? 0 : 7 - day)); return value; }

export default async function StudyPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string }> }) {
  const user = await requireUser();
  const { id } = await params;
  const feedback = await searchParams;
  const study = await prisma.study.findUnique({
    where: { id },
    include: {
      client: true,
      responsibleTechnologist: true,
      standard: { include: { definitions: { orderBy: { sortOrder: "asc" } } } },
      components: true,
      criteria: { include: { testDefinition: true, currentVersion: true, versions: { orderBy: { version: "desc" }, take: 3, include: { author: true } } } },
      samples: { orderBy: [{ nominalDate: "asc" }, { code: "asc" }], include: { initialMeasurement: true, tests: { include: { testDefinition: true, studyCriterion: { include: { currentVersion: true } }, result: true } }, microbiologyResult: true } },
      auditEvents: { orderBy: { createdAt: "desc" }, take: 24, include: { author: true } },
    },
  });
  if (!study) notFound();

  const requiredSamples = study.samples.filter((sample) => sample.role !== SampleRole.REFERENCE || sample.referenceStatus === "ACTIVATED");
  const completed = requiredSamples.filter((sample) => sample.executionStatus === "COMPLETED").length;
  const results = study.samples.flatMap((sample) => sample.tests.flatMap((test) => test.result ? [{ sample, test, result: test.result }] : []));
  const nokResults = results.filter((item) => item.result.currentEvaluation === Evaluation.NOK);
  const microNokSamples = study.samples.filter((sample) => sample.microbiologyResult?.evaluation === Evaluation.NOK);
  const references = study.samples.filter((sample) => sample.role === SampleRole.REFERENCE);
  const canManage = user.role === UserRole.TECHNOLOGIST || user.role === UserRole.ADMIN;
  const normalComponents = study.components.filter((item) => item.kind !== "Badanie mikrobiologiczne");
  const microbiologyScope = study.components.filter((item) => item.kind === "Badanie mikrobiologiczne");
  const initialDone = study.samples.length > 0 && study.samples.every((sample) => { const m = sample.initialMeasurement; if (!m) return false; return (m.initialWeightG != null || (m.weightNotPerformed && Boolean(m.weightNotPerformedReason))) && (!study.aerosol || m.initialPressureBar != null || (m.pressureNotPerformed && Boolean(m.pressureNotPerformedReason))); });
  const now = new Date();
  const incompleteScheduled = study.samples.filter((sample) => sample.role !== SampleRole.REFERENCE && sample.executionStatus !== "COMPLETED" && sample.nominalDate);
  const overdue = incompleteScheduled.filter((sample) => sample.nominalDate! < now && now <= weekEnd(sample.nominalDate!)).length;
  const expired = incompleteScheduled.filter((sample) => now > weekEnd(sample.nominalDate!)).length;

  return <AppShell user={user} active="studies">
    <div className="topline"><div><div className="eyebrow">{study.studyNumber} · {study.client.name}</div><h1>{study.projectName}</h1><div className="subtle">Technolog: {study.responsibleTechnologist.name} · Start: {study.startDate.toLocaleDateString("pl-PL")} · {study.standard?.name ?? "bez standardu"}</div></div><div className="top-actions study-top-actions"><span className={`badge ${study.status === StudyStatus.ACTIVE ? "teal" : study.status === StudyStatus.COMPLETED ? "success" : study.status === StudyStatus.INTERRUPTED ? "danger" : "neutral"}`}>{statusLabel[study.status]}</span>{study.status === StudyStatus.DRAFT && canManage && <Link href={`/studies/${study.id}/edit`} className="btn btn-secondary">Edytuj</Link>}{study.samples.length > 0 && <Link href={`/studies/${study.id}/labels`} className="btn btn-secondary">Etykiety</Link>}<Link href={`/studies/${study.id}/trends`} className="btn btn-secondary">Trendy</Link><a href={`/api/studies/${study.id}/export/excel`} className="btn btn-secondary">Excel</a><a href={`/api/studies/${study.id}/export/pdf`} className="btn btn-secondary">PDF</a><Link href="/studies" className="btn btn-secondary">← Zlecenia</Link></div></div>

    {feedback.error && <div className="save-banner danger-banner">{feedback.error === "reason" ? "Podaj wymagany powód operacji." : feedback.error === "no-reference" ? "Brak dostępnej próbki RF dla tego warunku przechowywania." : feedback.error === "criterion" ? "Nieprawidłowa wartość kryterium." : decodeURIComponent(feedback.error)}</div>}
    {study.status === StudyStatus.DRAFT && <section className="draft-callout"><div><div className="eyebrow">Zlecenie robocze</div><h2>Gotowe do przekazania?</h2><p>Po przekazaniu zamrozimy standard i zakres badań oraz wygenerujemy fizyczne próbki. Data rozpoczęcia nie może być wcześniejsza niż dzień przekazania.</p></div>{canManage && <form method="post" action={`/api/studies/${study.id}/lifecycle`}><input type="hidden" name="intent" value="handover" /><button className="btn btn-primary btn-large" type="submit">Przekaż do Laboratorium</button></form>}</section>}
    {study.status === StudyStatus.ACTIVE && !initialDone && <section className="info-callout warning-callout"><div><strong>Najpierw badania wstępne</strong><span>Laboratorium musi zapisać wagę początkową wszystkich próbek oraz ciśnienie dla aerozoli. Dopiero potem otworzą się badania właściwe.</span></div><Link className="btn btn-secondary" href="/lab">Otwórz Laboratorium</Link></section>}
    {study.status === StudyStatus.INTERRUPTED && <section className="info-callout warning-callout"><div><strong>Badanie zostało przerwane</strong><span>{study.interruptionReason || "Brak opisu powodu."} Wszystkie dane pozostają tylko do odczytu.</span></div></section>}

    <section className="kpi-grid"><div className="kpi teal"><div className="kpi-value">{study.samples.length ? `${completed}/${requiredSamples.length}` : "—"}</div><div className="kpi-label">Próbki wykonane</div><div className="kpi-note">niewykorzystane RF nie są liczone</div></div><div className="kpi danger"><div className="kpi-value">{nokResults.length + microNokSamples.length}</div><div className="kpi-label">Aktualne NOK</div><div className="kpi-note">według bieżących kryteriów</div></div><div className="kpi warning"><div className="kpi-value">{overdue}</div><div className="kpi-label">Zaległe</div><div className="kpi-note">po terminie, w bieżącym sprincie</div></div><div className={`kpi ${expired ? "danger" : ""}`}><div className="kpi-value">{expired}</div><div className="kpi-label">Przeterminowane</div><div className="kpi-note">przeniesione z wcześniejszych sprintów</div></div></section>
    <div className="study-tabs"><a href="#summary" className="active">Podsumowanie</a><a href="#results">Wyniki</a><Link href={`/studies/${study.id}/trends`}>Trendy</Link><a href="#samples">Próbki</a><a href="#criteria">Kryteria</a><a href="#history">Historia</a></div>

    <section className="section" id="summary"><div className="section-head"><div><div className="eyebrow">Specyfikacja zlecenia</div><div className="section-title">Podsumowanie</div></div></div><div className="summary-grid"><div className="summary-card"><span>Projekt / ETS</span><strong>{study.projectName}</strong><small>{study.etsNumber || "Brak numeru ETS"}</small></div><div className="summary-card"><span>Produkt</span><strong>{study.aerosol ? "Aerozol" : "Nieaerozol"}</strong><small>{study.aerosol ? `${study.gasType || "gaz nieokreślony"} · ${study.volumeMl ?? "—"} ml` : `${study.volumeMl ?? "—"} ml`}</small></div><div className="summary-card"><span>Produkcja / start</span><strong>{study.productionDate.toLocaleDateString("pl-PL")}</strong><small>Start {study.startDate.toLocaleDateString("pl-PL")}</small></div><div className="summary-card"><span>RF dostępne</span><strong>{references.filter((ref) => ref.referenceStatus === "AVAILABLE").length}</strong><small>{references.length} próbek referencyjnych łącznie</small></div></div>{normalComponents.length > 0 && <div className="table-card compact-table"><table><thead><tr><th>Rodzaj</th><th>Kod</th><th>Nazwa</th><th>Dostawca</th></tr></thead><tbody>{normalComponents.map((component) => <tr key={component.id}><td>{component.kind}</td><td>{component.code || "—"}</td><td className="primary-cell">{component.name}</td><td>{component.supplier || "—"}</td></tr>)}</tbody></table></div>}{microbiologyScope.length > 0 && <details className="micro-scope study-micro-scope"><summary>Zakres badań mikrobiologicznych <span>{microbiologyScope.length} wybranych pozycji</span></summary><div className="micro-grid">{microbiologyScope.map((item) => <div className="micro-option static" key={item.id}><span>{item.name}</span></div>)}</div></details>}</section>

    {(nokResults.length > 0 || microNokSamples.length > 0) && <section className="section" id="attention"><div className="section-head"><div><div className="eyebrow">Wymaga uwagi</div><div className="section-title">Wyniki NOK</div></div></div><div className="table-card"><table><thead><tr><th>Próbka</th><th>Badanie</th><th>Wynik</th><th>Warunek</th><th>Zapisano</th><th>RF / OOS</th></tr></thead><tbody>{nokResults.map(({ sample, test, result }) => { const availableRef = references.some((ref) => ref.referenceStatus === "AVAILABLE" && ref.storageCondition === sample.storageCondition); return <tr key={result.id}><td className="primary-cell">{sample.code}</td><td>{test.testDefinition.name}</td><td><span className="badge danger">{resultText(result, test.testDefinition.unit)}</span></td><td>{sample.storageCondition}</td><td>{result.updatedAt.toLocaleString("pl-PL")}</td><td>{study.status === StudyStatus.ACTIVE && canManage && availableRef ? <form method="post" action={`/api/studies/${study.id}/attention`} className="rf-action"><input type="hidden" name="intent" value="activate-reference" /><input type="hidden" name="sourceResultId" value={result.id} /><input name="reason" placeholder="Powód użycia RF" defaultValue="Weryfikacja wyniku NOK" required /><button className="btn btn-small btn-secondary" type="submit">Użyj RF</button></form> : <span className="subtle">{availableRef ? "—" : "Brak RF dla warunku"}</span>}</td></tr>; })}{microNokSamples.map((sample) => <tr key={`micro-${sample.id}`}><td className="primary-cell">{sample.code}</td><td>Mikrobiologia — wynik zbiorczy</td><td><span className="badge danger">NOK</span></td><td>{sample.storageCondition}</td><td>{sample.microbiologyResult!.updatedAt.toLocaleString("pl-PL")}</td><td className="subtle">Decyzja Technologa</td></tr>)}</tbody></table></div></section>}

    <section className="section" id="results"><div className="section-head"><div><div className="eyebrow">Dane laboratoryjne</div><div className="section-title">Wyniki</div><div className="subtle">Ocena pokazuje zgodność według aktualnej wersji kryterium.</div></div></div><div className="table-card results-overview"><table><thead><tr><th>Próbka</th><th>Checkpoint</th><th>Warunek</th><th>Badanie</th><th>Wynik</th><th>Kryterium</th><th>Ocena</th></tr></thead><tbody>{results.length ? results.map(({ sample, test, result }) => <tr key={result.id}><td className="primary-cell">{sample.code}</td><td>{sample.checkpointLabel || "RF"}</td><td>{sample.storageCondition}</td><td>{test.testDefinition.name}</td><td>{resultText(result, test.testDefinition.unit)}</td><td>{criterionText(test.studyCriterion?.currentVersion)}</td><td><span className={`badge ${result.currentEvaluation === Evaluation.NOK ? "danger" : result.currentEvaluation === Evaluation.OK ? "success" : "neutral"}`}>{result.currentEvaluation === Evaluation.NOT_APPLICABLE ? "—" : result.currentEvaluation}</span></td></tr>) : <tr><td colSpan={7}><div className="empty-state"><strong>Brak zapisanych wyników</strong><span>Pojawią się tutaj po rozpoczęciu pracy Laboratorium.</span></div></td></tr>}{study.samples.filter((sample) => sample.microbiologyResult).map((sample) => <tr key={`micro-result-${sample.id}`}><td className="primary-cell">{sample.code}</td><td>{sample.checkpointLabel || "—"}</td><td>{sample.storageCondition}</td><td>Mikrobiologia — wynik zbiorczy</td><td>{sample.microbiologyResult!.evaluation}</td><td>OK</td><td><span className={`badge ${sample.microbiologyResult!.evaluation === Evaluation.NOK ? "danger" : "success"}`}>{sample.microbiologyResult!.evaluation}</span></td></tr>)}</tbody></table></div></section>

    <section className="section" id="samples"><div className="section-head"><div><div className="eyebrow">Plan badania</div><div className="section-title">Próbki</div></div><div className="top-actions">{study.samples.length > 0 && <Link className="section-link" href={`/studies/${study.id}/labels`}>Drukuj etykiety →</Link>}{study.status === StudyStatus.ACTIVE && <Link className="section-link" href="/lab">Laboratorium →</Link>}</div></div><div className="table-card"><table><thead><tr><th>Kod</th><th>Rola</th><th>Checkpoint</th><th>Termin</th><th>Warunek</th><th>Wstępne</th><th>Realizacja</th></tr></thead><tbody>{(study.samples.length ? study.samples : study.standard?.definitions ?? []).map((sample) => { const isGenerated = "studyId" in sample; const role = sample.role; const initial = isGenerated ? sample.initialMeasurement : null; const initialOk = initial ? (initial.initialWeightG != null || initial.weightNotPerformed) && (!study.aerosol || initial.initialPressureBar != null || initial.pressureNotPerformed) : false; return <tr key={sample.id}><td className="primary-cell">{sample.code}</td><td>{role === "REFERENCE" ? <span className={`badge ${isGenerated && sample.referenceStatus === "ACTIVATED" ? "teal" : "warning"}`}>{isGenerated && sample.referenceStatus === "ACTIVATED" ? "RF aktywowana" : "RF / OOS backup"}</span> : role === "MICROBIOLOGY" ? "Mikrobiologia" : "Standardowa"}</td><td>{sample.checkpointLabel ?? "—"}</td><td>{isGenerated ? sample.nominalDate?.toLocaleDateString("pl-PL") ?? "—" : sample.checkpointDays == null ? "—" : `+${sample.checkpointDays} dni`}</td><td>{sample.storageCondition}</td><td>{isGenerated ? <span className={`badge ${initialOk ? "success" : "warning"}`}>{initialOk ? "Gotowe" : "Do wykonania"}</span> : "po przekazaniu"}</td><td>{isGenerated ? <Link className="section-link" href={`/lab/sample/${sample.id}`}>{role === "REFERENCE" ? sample.referenceStatus : sample.executionStatus}</Link> : "—"}</td></tr>; })}</tbody></table></div></section>

    <section className="section" id="criteria"><div className="section-head"><div><div className="eyebrow">Specyfikacja</div><div className="section-title">Kryteria akceptacji</div><div className="subtle">Zakres badań jest zamrożony po przekazaniu. W aktywnym badaniu Technolog może zmienić wyłącznie wartość istniejącego kryterium.</div></div></div><div className="table-card"><table><thead><tr><th>Badanie</th><th>Typ</th><th>Aktualne kryterium</th><th>Wersja</th><th>Ostatnia zmiana</th></tr></thead><tbody>{study.criteria.map((criterion) => { const v = criterion.currentVersion; return <tr key={criterion.id}><td className="primary-cell">{criterion.testDefinition.name}</td><td>{criterion.kind}</td><td>{criterionText(v)}</td><td>v{v?.version ?? 1}</td><td>{v?.reason || "Kryterium początkowe"}</td></tr>; })}</tbody></table></div>
      {study.status === StudyStatus.ACTIVE && canManage && <div className="criterion-edit-list">{study.criteria.map((criterion) => { const v = criterion.currentVersion; if (!v) return null; const numeric = criterion.kind === CriterionKind.RANGE || criterion.kind === CriterionKind.MINIMUM || criterion.kind === CriterionKind.MAXIMUM; return <details className="criterion-editor" key={criterion.id}><summary><span><strong>{criterion.testDefinition.name}</strong><small>Aktualnie v{v.version}</small></span><span>Zmień wartość kryterium</span></summary><form method="post" action={`/api/studies/${study.id}/attention`}><input type="hidden" name="intent" value="change-criterion" /><input type="hidden" name="criterionId" value={criterion.id} />{numeric ? <div className="criterion-editor-values"><label>Minimum<input name="minValue" type="number" step="any" defaultValue={v.minValue ?? ""} /></label><label>Maksimum<input name="maxValue" type="number" step="any" defaultValue={v.maxValue ?? ""} /></label></div> : criterion.kind === CriterionKind.EXPECTED_VALUE ? <label>Wartość oczekiwana<input name="expectedText" defaultValue={v.expectedText ?? ""} required /></label> : criterion.kind === CriterionKind.BOOLEAN_EXPECTED ? <label>Wartość oczekiwana<select name="expectedBoolean" defaultValue={v.expectedBoolean ? "true" : "false"}><option value="true">TAK</option><option value="false">NIE</option></select></label> : null}<label className="criterion-reason">Uzasadnienie zmiany *<input name="reason" placeholder="Dlaczego kryterium się zmienia?" required /></label><button className="btn btn-primary" type="submit">Zapisz nową wersję</button></form>{criterion.versions.length > 1 && <div className="criterion-history">{criterion.versions.map((version) => <div key={version.id}><strong>v{version.version}</strong><span>{version.createdAt.toLocaleString("pl-PL")} · {version.author.name}</span><small>{version.reason || "Kryterium początkowe"}</small></div>)}</div>}</details>; })}</div>}
    </section>

    <section className="section" id="history"><div className="section-head"><div><div className="eyebrow">Traceability</div><div className="section-title">Ostatnia aktywność</div></div></div><div className="activity-list">{study.auditEvents.length ? study.auditEvents.map((event) => <div className="activity-row" key={event.id}><span>{event.createdAt.toLocaleString("pl-PL")}</span><strong>{event.message}</strong><small>{event.author?.name ?? "System"}</small></div>) : <div className="empty-state"><span>Brak dodatkowych zdarzeń w historii.</span></div>}</div></section>

    {study.status === StudyStatus.DRAFT && canManage && <section className="danger-zone"><div><strong>Anuluj zlecenie</strong><span>Anulowanie jest nieodwracalne i wymaga podania powodu.</span></div><form method="post" action={`/api/studies/${study.id}/lifecycle`} className="inline-form"><input type="hidden" name="intent" value="cancel" /><input name="reason" placeholder="Powód anulowania" required /><button className="btn btn-danger" type="submit">Anuluj</button></form></section>}
    {study.status === StudyStatus.ACTIVE && canManage && <section className="danger-zone"><div><strong>Przerwij badanie</strong><span>Przerwanie jest nieodwracalne. Zlecenie i wyniki pozostaną w historii, ale znikną z kolejki Laboratorium.</span></div><form method="post" action={`/api/studies/${study.id}/lifecycle`} className="inline-form"><input type="hidden" name="intent" value="interrupt" /><input name="reason" placeholder="Powód przerwania" required /><button className="btn btn-danger" type="submit">Przerwij</button></form></section>}
  </AppShell>;
}
